application: islapeu
version: rc2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /favicon.png
  static_files: static/images/favicon.png
  upload: static/images/favicon.png
  
- url: /.*
  script: main.py
  